Update citizens.json
nyabla/silly.city-webring pull request #30
Opened 2024-05-11 00:36 UTC by eightheve

2024-05-11 07:40 UTC, nyabla requested changes
plz remove the last comma. trailing commas are not valid JSON.

2024-05-22 06:57 UTC, eightheve commented
my bad, trailing comma is gone.

2024-06-17 15:27 UTC, nyabla approved these changes

2024-06-17 15:28 UTC, merged

2024-06-17 15:28 UTC, nyabla commented
welcome to silly city! sorry for the delay